### ISSUE TITLE
Center Tabs

### ISSUE THREAD

**Issue by MobileMon** [moyunmo/CMTabbarView#1]
Any way to center the tabs horizontally when they don't take up the whole screen width?

**Comment by moyunmo** [comment]
If I understand your question correctly, you can use the fuction "- (void)scrollToItemAtIndexPath:(NSIndexPath *)indexPath atScrollPosition:(UICollectionViewScrollPosition)scrollPosition animated:(BOOL)animated"

**Comment by smamczak** [comment]
@moyunmo I think that @MobileMon wanted something like this. I would appreciate it also as an option to your component.

![img2](https://cloud.githubusercontent.com/assets/17873294/25794174/219be3fe-33d0-11e7-93d6-0b6a015d0872.png)

**Comment by moyunmo** [comment]
fixed
