### ISSUE TITLE
Initialisation via Storyboard

### ISSUE THREAD

**Issue by brunomiguensolx** [moyunmo/CMTabbarView#2]
Hi,

First of all, congratulations for your work, isn't  a huge project but works well and have a easy usage and instalation.

My suggestion is to you make the ability to initialise using a Storyboard, i think is a good feature to have because i tried to initialize and the final result wasn't the same.

Other suggestion, linked with the previous one, is to add the ```@IBOutlet``` to the ```delegate``` and ```dataSource```, in case of you add the possibility to create a ```CMTabbarView``` via Storyboard.

Thank you and good luck.

**Comment by moyunmo** [comment]
Thank you for your advice, I will seize the time to update
