### ISSUE TITLE
Setting not the first one as default tab

### ISSUE THREAD

**Issue by appfabtech** [moyunmo/CMTabbarView#3]
First of all thanks for the great component!
I'm trying to initializate it with a tab different from first one as default. 
The VC receives the selected tab and try to set it in the component
	_tabbarView.defaultSelectedIndex = start;
	[_tabbarView setTabIndex:start animated:true];
But both the tab 0 and the one I want to select are selected. Also even with animated = true, the selected tab is not centered on screen

Am I doing something wrong?
Thanks
Paolo
<img width="376" alt="screen shot 2017-03-21 at 19 02 45" src="https://cloud.githubusercontent.com/assets/437895/24162837/036b1f1c-0e69-11e7-8482-cbaf76fcd53a.png">

**Comment by appfabtech** [comment]
update:
moving the code in
- (void) viewDidAppear:(BOOL)animated
{
	[super viewDidAppear:animated];
	
	_tabbarView.defaultSelectedIndex = start;
	[_tabbarView setTabIndex:start animated:false];
}

it works, but there is the nasty update of screen after it has been already rendered.
viewWillAppear is not enough.
In
- (void)updateTabbarForIndex:(NSInteger)index animated:(BOOL)animated
the
    CMTabbarCollectionViewCell *cell = [self cellAtIndex:index];
returns nil. Only in viewDidAppear is not nil

**Comment by moyunmo** [comment]
![image](https://cloud.githubusercontent.com/assets/5546839/24180587/aa70d464-0ef0-11e7-81ba-738b1467f621.png)


I have updated this example, you can download the example to run, whether to solve your issue？

**Comment by moyunmo** [comment]
![5f954628-85f8-482a-b787-b6bbec5f40bd](https://cloud.githubusercontent.com/assets/5546839/24180638/faf18226-0ef0-11e7-9c97-e2ff99920011.png)

I have updated this example, you can download the example to run, whether to solve your issue？
