### ISSUE TITLE
Setting the default index of tab that is off the screen

### ISSUE THREAD

**Issue by shekunsky** [moyunmo/CMTabbarView#5]
Hi!
Thanks for your work. 
I have a trouble with setting default tab index that is off the screen.
If i have 10 tab items and screen shows only 4 first, then if i will set the default index > 4 - hi is not appears at screen, until i'll scroll it.
How i can do it?
Thanks.

**Comment by moyunmo** [comment]
Thank you for your issue!
I've already fixed it,
pod 'CMTabbarView' 0.1.4

**Comment by shekunsky** [comment]
Yes, now it working.
Thanks a LOT!
